# Generated by Django 5.1.5 on 2025-03-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_manga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='ratings',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='manga',
            name='chapter_count',
            field=models.PositiveIntegerField(),
        ),
    ]
