# Generated by Django 5.1.5 on 2025-03-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_ratings_manga_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='chapter_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
